baseURL = "https://lassebredmose.github.io/Biking_to_a_cleaner_future/"
title = "Biking to a cleaner future"
subtitle = "This is the subtitle"
description = "This is a description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Maria Mandrup Fogh", "Enny Tao", "Lasse Enevold Bredmose"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/lassebredmose/Biking_to_a_cleaner_future"
    title = "Biking"
    subtitle = "-to a cleaner future"
    description = "Analysing Åsepige data for at predictre fremtidens trends indenfor cykling"