baseURL = "https://lassebredmose.github.io/Biking_to_a_cleaner_future/"
title = "Biking to a cleaner future"
subtitle = "This is the subtitle"
description = "This is a description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Maria Mandrup Fogh", "Enny Tao", "Lasse Enevold Bredmose"]
    notebook = "https://deepnote.com/@maria-fogh/SocialDataProject2022-61ec0a5b-e327-402f-95c1-91c4aeb91c25"
    data = "https://github.com/LasseBredmose/social_data_2022_project/tree/main/data"
    github = "https://github.com/LasseBredmose/social_data_2022_project"
    title = "Biking"
    subtitle = "to a cleaner future"
    description = "Analysing Åsepige data for at predictre fremtidens trends indenfor cykling"