baseURL = "https://lassebredmose.github.io/Biking_to_a_cleaner_future/"
title = "Biking to a cleaner future"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Maria Krog", "Enny Tao", "Lasse Bredmose"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/lassebredmose/Biking_to_a_cleaner_future"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

